import { CitizenIdentity, CitizenNeeds } from '../../types/citizenAgent';
import { NeedSystem } from './NeedSystem';
import { BeliefSystem } from './BeliefSystem';
import { MemorySystem } from './MemorySystem';
import { GoalSystem } from './GoalSystem';
import { RelationshipSystem } from './RelationshipSystem';
import { PerceptionEngine } from './PerceptionEngine';
import { AgentLoopGuard } from './AgentLoopGuard';
import { ReflectionSystem } from './ReflectionSystem';
import { CognitionEngine } from './CognitionEngine';
import { CitizenId, ControlMode } from '../../types/citizen';
import { worldEventBus } from '../simulation/WorldEventBus';
import { navigationSystem } from './NavigationSystem';
import { activityDurationManager } from '../simulation/ActivityDurationManager';
import { worldSimulationEngine } from '../simulation/WorldSimulationEngine';
import { getSemanticLocationAtPosition } from '../../types/locations';

import { EmotionSystem } from './EmotionSystem';
import { GoalStackEngine } from './GoalStackEngine';

export class CitizenAgent {
  public identity: CitizenIdentity;
  public needSystem: NeedSystem;
  public emotionSystem: EmotionSystem;
  public goalStackEngine: GoalStackEngine;
  public beliefSystem: BeliefSystem;
  public memorySystem: MemorySystem;
  public goalSystem: GoalSystem;
  public relationshipSystem: RelationshipSystem;
  public perceptionEngine: PerceptionEngine;
  public loopGuard: AgentLoopGuard;
  public reflectionSystem: ReflectionSystem;
  public cognitionEngine: CognitionEngine;

  private controlMode: ControlMode = 'AI';
  private listeners: Set<() => void> = new Set();
  public lastPos: [number, number, number];
  private lastReasoningTriggerTime: number = 0;

  private processedEventIds: Set<string> = new Set();

  constructor(identity: CitizenIdentity, initialNeeds?: Partial<CitizenNeeds>, initialBeliefs?: string[]) {
    this.identity = identity;
    this.lastPos = [0, 0, 0];

    this.needSystem = new NeedSystem(initialNeeds);
    this.emotionSystem = new EmotionSystem(0.2, 0.3);
    this.goalStackEngine = new GoalStackEngine();
    this.beliefSystem = new BeliefSystem(initialBeliefs);
    this.memorySystem = new MemorySystem(identity.id);
    this.goalSystem = new GoalSystem();
    this.relationshipSystem = new RelationshipSystem(identity.id);
    this.perceptionEngine = new PerceptionEngine(identity.id);
    this.loopGuard = new AgentLoopGuard();
    this.reflectionSystem = new ReflectionSystem();

    this.cognitionEngine = new CognitionEngine(
      this.identity,
      this.needSystem,
      this.beliefSystem,
      this.memorySystem,
      this.goalSystem,
      this.relationshipSystem,
      this.perceptionEngine,
      this.loopGuard,
      this.reflectionSystem,
      this.emotionSystem
    );

    // Subscribe to WorldEventBus for event-driven wakeups
    worldEventBus.subscribe((evt) => {
      // 1. Idempotency Check: Ignore already processed events
      if (this.processedEventIds.has(evt.id)) return;
      this.processedEventIds.add(evt.id);
      if (this.processedEventIds.size > 200) {
        const first = this.processedEventIds.values().next().value;
        if (first) this.processedEventIds.delete(first);
      }

      // 2. Prevent Self-Response: Ignore events generated by self as actor or speaker
      if (evt.payload?.actorId === this.identity.id || evt.payload?.speaker === this.identity.id) {
        return;
      }

      // 3. Listener / Target Filter: If event targets a specific citizen, ensure it targets this citizen
      const targetId = evt.payload?.targetId || evt.payload?.listener;
      if (targetId && targetId !== this.identity.id) {
        return;
      }

      const isSocialEvent = evt.type.includes('TALK') || evt.type.includes('INTERACT') || evt.type.includes('ASK') || evt.type.includes('GREET') || evt.type.includes('HELP');
      const requiresResponse = evt.payload?.requiresResponse !== false;

      if (this.controlMode === 'AI') {
        if ((isSocialEvent && requiresResponse) || !this.cognitionEngine.getIsBusy()) {
          if (isSocialEvent && requiresResponse) {
            navigationSystem.clearIntention(this.identity.id);
            activityDurationManager.clearActivity(this.identity.id);
          }
          const dummyPos: Record<CitizenId, [number, number, number]> = {
            ben: this.identity.id === 'ben' ? this.lastPos : [0, 0, 0],
            julie: this.identity.id === 'julie' ? this.lastPos : [0, 0, 0],
            ravi: this.identity.id === 'ravi' ? this.lastPos : [0, 0, 0],
          };
          const eventText = evt.description || `Event: ${evt.type}`;
          console.log(`[EVENT_WAKEUP] [${this.identity.name.toUpperCase()}] Processing event "${eventText}" (Id: ${evt.id})`);
          this.cognitionEngine.think(this.lastPos, dummyPos, eventText);
          this.notify();

        }
      }
    });

    // Initial default goal setup
    const initialGoalDesc = identity.id === 'ben'
      ? 'Manage wheat farm, irrigate crops, and inspect farm buildings'
      : 'Manage village bakery, prepare fresh food, and explore surrounding area';
    this.goalSystem.createGoal(initialGoalDesc, 5, 'Initial autonomous life motivation');
  }

  public subscribe(listener: () => void): () => void {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  }

  private notify() {
    this.listeners.forEach((l) => l());
  }

  public getControlMode(): ControlMode {
    return this.controlMode;
  }

  public setControlMode(mode: ControlMode) {
    this.controlMode = mode;
    if (mode === 'MANUAL') {
      navigationSystem.clearIntention(this.identity.id);
    }
    this.notify();
  }

  /**
   * Main simulation frame update loop for the agent
   */
  public update(
    currentPos: [number, number, number],
    currentRotY: number,
    delta: number,
    allPositions: Record<CitizenId, [number, number, number]>,
    simDeltaMinutes: number,
    ambientTemp: number
  ) {
    this.lastPos = currentPos;

    // 1. Tick physical needs and emotion state
    const isWorking = navigationSystem.getCurrentIntention(this.identity.id) !== null;
    this.needSystem.update(simDeltaMinutes, ambientTemp, isWorking);
    this.emotionSystem.update(simDeltaMinutes, this.needSystem.getNeeds());

    if (this.controlMode !== 'AI') return;

    // 2. Navigation update
    const navResult = navigationSystem.update(currentPos, currentRotY, delta, this.identity.id);

    // 3. Activity Duration update
    const totalSimMins = worldSimulationEngine.getTotalSimulationMinutes();
    const durationResult = activityDurationManager.update(this.identity.id, totalSimMins);

    // 4. Event-Driven & Idle Cognition Triggers
    const activeGoal = this.goalSystem.getActiveGoal();
    const isNavigating = navigationSystem.getCurrentIntention(this.identity.id) !== null;
    const isActivityActive = activityDurationManager.isActivityActive(this.identity.id);
    const currentDecision = this.cognitionEngine.getCurrentDecision();
    const now = Date.now();
    const timeSinceLastTrigger = now - this.lastReasoningTriggerTime;

    if (!isNavigating && !isActivityActive && !this.cognitionEngine.getIsThinking()) {
      if (!currentDecision) {
        // Initial startup trigger: No decision made yet!
        this.lastReasoningTriggerTime = now;
        this.cognitionEngine.think(currentPos, allPositions, 'Initial startup reasoning');
      } else if (navResult.isCompleted) {
        if (navResult.travelMemory) {
          this.memorySystem.addEpisodicMemory(
            navResult.travelMemory,
            getSemanticLocationAtPosition(currentPos),
            0.2,
            ['travel', 'arrival']
          );
        }
        this.cognitionEngine.clearCurrentDecision();
        this.lastReasoningTriggerTime = now;
        this.cognitionEngine.think(currentPos, allPositions, 'Arrived at destination');
      } else if (durationResult.isCompleted) {
        this.cognitionEngine.clearCurrentDecision();
        this.lastReasoningTriggerTime = now;
        this.cognitionEngine.think(currentPos, allPositions, 'Activity duration completed');
      } else if (navResult.isInvalidated) {
        this.cognitionEngine.clearCurrentDecision();
        this.lastReasoningTriggerTime = now;
        this.cognitionEngine.think(currentPos, allPositions, 'Navigation failed');
      } else if (!activeGoal || activeGoal.status !== 'ACTIVE') {
        this.cognitionEngine.clearCurrentDecision();
        this.lastReasoningTriggerTime = now;
        this.cognitionEngine.think(currentPos, allPositions, 'No active goal');
      } else if (timeSinceLastTrigger > 3500) {
        // Idle heartbeat trigger: Citizen has no active tool/movement running for 3.5 seconds
        this.cognitionEngine.clearCurrentDecision();
        this.lastReasoningTriggerTime = now;
        this.cognitionEngine.think(currentPos, allPositions, 'Idle tick - evaluating next action');
      }
    }

    // Determine visual animation state for 3D character rendering
    let animState = navResult.animState;
    const activeActivity = activityDurationManager.getActiveActivity(this.identity.id);
    if (activeActivity && activeActivity.status === 'ACTIVE') {
      const act = activeActivity.action.toUpperCase();
      if (act.includes('WATER')) animState = 'WATER_CROP' as any;
      else if (act.includes('HARVEST')) animState = 'HARVEST_CROP' as any;
      else if (act.includes('PLANT')) animState = 'PLANT_CROP' as any;
    }

    this.notify();
    return {
      ...navResult,
      animState,
    };
  }
}
