// Auto-generated by scripts/scan-animations.js - DO NOT EDIT MANUALLY
import { AnimationRegistryData } from './types';
import rawData from '../../../public/data/animation-memory.json';

export const ANIMATION_MEMORY_DATA = rawData as AnimationRegistryData;
